[package]
name = "readcon-core"
version = "0.1.1"
edition = "2024"
rust-version = "1.88"
description = "An oxidized single and multiple CON file reader and writer with FFI bindings for ergonomic C/C++ usage."
repository = "https://github.com/lode-org/readcon-rs"
keywords = ["Parser", "comp-chem", "file-format"]
categories = ["filesystem", "parser-implementations", "science"]
license = "MIT"

[dev-dependencies]
cog = "0.1.0"
criterion = { version = "0.6.0", features = ["html_reports"] }

[[bench]]
name = "iterator_bench"
harness = false

[build-dependencies]
cbindgen = "0.29.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

