#!/usr/bin/env python3
"""Write CPC table fragments from committed artifacts. Org never types the numbers."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parents[1] / "src" / "figures" / "generated"

HEADER = "% Auto-generated by paper/cpc/scripts/gen_tables.py -- do not edit by hand.\n"


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


def _write(name: str, body: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(HEADER + body)


def _ms(v: float, nd: int = 3) -> str:
    return f"${v:.{nd}f}$"


def _int_tex(n: int) -> str:
    return "$" + f"{n:,}".replace(",", r"\,") + "$"


def _bytes_tex(n: int) -> str:
    return _int_tex(n)


def gen_macros(traj: dict, h5: dict, wall_scale: dict, cmp: dict) -> str:
    frame = int(h5["con_size_bytes"]) // int(traj["n_frames"])
    seq = float(wall_scale["sequential_ms"])
    auto = float(wall_scale["auto_ms"])
    speedup = seq / auto
    return r"""
\newcommand{\conFrameBytes}{%s}
\newcommand{\conConcatBytes}{%s}
\newcommand{\wallNativeMs}{%.3f}
\newcommand{\ioSeqMs}{%.3f}
\newcommand{\ioAutoMs}{%.3f}
\newcommand{\ioSpeedup}{%.1f}
\newcommand{\wallCommit}{%s}
\newcommand{\ioCommit}{%s}
\newcommand{\ioHost}{%s}
\newcommand{\ioNcpus}{%s}
""" % (
        _bytes_tex(frame).strip("$"),
        _bytes_tex(int(h5["con_size_bytes"])).strip("$"),
        float(traj["readcon_con_median_ms"]),
        seq,
        auto,
        speedup,
        traj["commit"],
        wall_scale["commit"],
        wall_scale["host"],
        wall_scale["ncpus"],
    )


def gen_cachegrind() -> str:
    rst = (ROOT / "docs/source/_generated/cachegrind_results.rst").read_text()
    rows = {
        "parse_multi_2x4": (50, None),
        "parse_cuh2_218": (20, None),
        "parse_100_frames": (10, None),
        "forward_100_frames": (10, None),
        "write_100_frames": (10, None),
        "chemfiles_xyz_path": (50, None),
        "float_fast_float2": (r"$10^{4}$ fields", None),
        "float_std_parse": (r"$10^{4}$ fields", None),
    }
    for m in re.finditer(
        r"``([a-z0-9_]+)``\s*\n\s*-\s*([0-9,]+)", rst
    ):
        name, raw = m.group(1), m.group(2)
        if name in rows:
            repeats, _ = rows[name]
            rows[name] = (repeats, int(raw.replace(",", "")))
    missing = [k for k, v in rows.items() if v[1] is None]
    if missing:
        raise SystemExit(f"cachegrind rst missing rows: {missing}")
    body = [
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{Cachegrind instruction counts (I-refs). Lower is better on",
        r"the same CI image. Source:",
        r"\texttt{docs/source/\_generated/cachegrind\_results.rst}.",
        r"\texttt{write\_100\_frames} is \texttt{ConFrameWriter::extend} into",
        r"a \texttt{Vec<u8>} on $100$ copies of \texttt{tiny\_cuh2.con}.",
        r"There is no Rayon scenario.}",
        r"\label{tab:cachegrind}",
        r"\begin{tabular}{lrr}",
        r"\toprule",
        r"Scenario & I-refs & Repeats \\",
        r"\midrule",
    ]
    order = [
        "parse_multi_2x4",
        "parse_cuh2_218",
        "parse_100_frames",
        "forward_100_frames",
        "write_100_frames",
        "chemfiles_xyz_path",
        "float_fast_float2",
        "float_std_parse",
    ]
    for name in order:
        repeats, n = rows[name]
        rep = repeats if isinstance(repeats, str) else str(repeats)
        tex_name = name.replace("_", r"\_")
        body.append(rf"\texttt{{{tex_name}}} & {_int_tex(n)} & {rep} \\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(body)


def gen_wall(traj: dict, h5: dict, cmp: dict) -> str:
    return "\n".join(
        [
            r"\begin{table}[ht]",
            r"\centering",
            r"\caption{Median wall times, 100 frames of the 218-atom",
            r"\texttt{cuh2.con} geometry, five repeats",
            rf"(\texttt{{benches/results/*.json}}, {traj['date_utc']}, tree",
            rf"\texttt{{{traj['commit']}}}). The three blocks are separate protocols; native",
            r"CON times are not averaged. H5MD is positions only",
            rf"({_bytes_tex(int(h5['h5md_size_bytes']))}\,B). h5py loads \texttt{{position/value}} only.",
            rf"\texttt{{CON.gz}} ({_bytes_tex(int(h5['con_gz_size_bytes']))}\,B) is gzip of repeated frames.",
            rf"\texttt{{CON.zst}} is {_bytes_tex(int(h5['con_zst_size_bytes']))}\,B; load time is absent (\texttt{{zstd}}",
            r"feature off). The \texttt{ase.io.eon} block uses a synthetic file",
            rf"of the same atom count ({_bytes_tex(int(cmp['file_size_bytes']))}\,B).}}",
            r"\label{tab:wall}",
            r"\begin{tabular}{@{}llr@{}}",
            r"\toprule",
            r"Protocol & Reader & Median (ms) \\",
            r"\midrule",
            rf"ASE / chemfiles vs CON & native CON & {_ms(traj['readcon_con_median_ms'])} \\",
            rf" & chemfiles XYZ$\to$CON & {_ms(traj['readcon_chemfiles_xyz_to_con_median_ms'])} \\",
            rf" & ASE \texttt{{.traj}} & {_ms(traj['ase_traj_median_ms'])} \\",
            rf" & ASE XYZ (lean) & {_ms(traj['ase_xyz_median_ms'])} \\",
            r"\midrule",
            rf"H5MD vs CON & native CON & {_ms(h5['readcon_con_ms'])} \\",
            rf" & chemfiles XYZ$\to$CON & {_ms(h5['readcon_chemfiles_xyz_ms'])} \\",
            rf" & MDAnalysis H5MD & {_ms(h5['mda_h5md_full_traj_ms'])} \\",
            rf" & h5py \texttt{{position/value}} & {_ms(h5['h5py_h5md_positions_only_ms'])} \\",
            rf" & native \texttt{{CON.gz}} & {_ms(h5['readcon_con_gz_ms'])} \\",
            r"\midrule",
            rf"Same CON text & ASE \texttt{{ase.io.eon}} & {_ms(cmp['readers']['ASE (ase.io.eon)']['median_ms'])} \\",
            rf" & C sscanf (eOn-style) & {_ms(cmp['readers']['C (sscanf) (eOn-style)']['median_ms'], 2)} \\",
            rf" & readcon path & {_ms(cmp['readers']['readcon-core (file path)']['median_ms'])} \\",
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]
    )


def gen_io(ws: dict) -> str:
    par = ws["parallel"]
    return "\n".join(
        [
            r"\begin{table}[ht]",
            r"\centering",
            r"\caption{Median wall times, 100 frames of the 218-atom",
            r"\texttt{cuh2.con} geometry, five repeats",
            rf"(\texttt{{benches/results/wall\_scale.json}}, {ws['date_utc']}, host",
            rf"\texttt{{{ws['host']}}}, {ws['ncpus']} CPUs, tree \texttt{{{ws['commit']}}},",
            r"\texttt{cargo run --release --example wall\_scale\_harness",
            r"--features parallel}). Sequential is",
            r"\texttt{frames\_from\_text(..., Some(1))}. Auto is the $48$\,KiB",
            r"policy on the global Rayon pool. Pinned pools use",
            r"\texttt{parse\_frames\_parallel\_with\_threads}. Write is",
            r"\texttt{ConFrameWriter} into a memory buffer of those frames. Do",
            r"not average these with Table~\ref{tab:wall}.}",
            r"\label{tab:io}",
            r"\begin{tabular}{@{}llr@{}}",
            r"\toprule",
            r"Path & Policy & Median (ms) \\",
            r"\midrule",
            rf"Parse & sequential (\texttt{{n=1}}) & {_ms(ws['sequential_ms'])} \\",
            rf" & auto (global pool) & {_ms(ws['auto_ms'])} \\",
            rf" & Rayon $n=2$ & {_ms(par['n2'])} \\",
            rf" & Rayon $n=4$ & {_ms(par['n4'])} \\",
            rf" & Rayon $n=8$ & {_ms(par['n8'])} \\",
            rf" & Rayon $n=16$ & {_ms(par['n16'])} \\",
            r"\midrule",
            rf"Write & buffer, 100 frames & {_ms(ws['write_100_frames_ms'])} \\",
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]
    )


def gen_neb() -> str:
    text = (ROOT / "resources/examples/neb_band.con").read_text()
    frames: list[tuple[int, str, float, float]] = []
    role = None
    for line in text.splitlines():
        if line.startswith("example NEB image"):
            m = re.search(r"\(([^)]+)\)", line)
            role = m.group(1) if m else "image"
        elif line.startswith("{"):
            meta = json.loads(line)
            frames.append(
                (
                    int(meta["neb_bead"]),
                    role or "image",
                    float(meta["energy"]),
                    float(meta["fmax"]),
                )
            )
    if len(frames) != 4:
        raise SystemExit(f"neb_band.con expected 4 frames, got {len(frames)}")
    rows = []
    for bead, role, e, fmax in frames:
        rows.append(rf"{bead} & {role} & ${e:.2f}$ & ${fmax:.2f}$ \\")
    e0 = frames[0][2]
    e1 = frames[1][2]
    barrier = e1 - e0
    _write(
        "neb_macros.tex",
        rf"\newcommand{{\nebBarrierEv}}{{{barrier:.2f}}}" + "\n",
    )
    return "\n".join(
        [
            r"\begin{table}[ht]",
            r"\centering",
            r"\caption{Declared NEB metadata recovered from",
            r"\texttt{resources/examples/neb\_band.con}. Spec~3, \texttt{units}",
            r"length=\texttt{angstrom}, energy=\texttt{eV},",
            r"\texttt{sections=[forces]}, \texttt{neb\_band=0}. $E$ and",
            r"$f_{\max}$ are line-2 JSON. They are not recomputed from the force",
            r"block.}",
            r"\label{tab:neb}",
            r"\begin{tabular}{@{}rlll@{}}",
            r"\toprule",
            r"Bead & Role & $E$ (eV) & $f_{\max}$ \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]
    )


def main() -> None:
    traj = _load(ROOT / "benches/results/ase_traj_vs_con.json")
    h5 = _load(ROOT / "benches/results/h5md_vs_con.json")
    cmp = _load(ROOT / "benches/results/compare_readers.json")
    ws = _load(ROOT / "benches/results/wall_scale.json")
    _write("macros.tex", gen_macros(traj, h5, ws, cmp))
    _write("cachegrind_table.tex", gen_cachegrind())
    _write("wall_table.tex", gen_wall(traj, h5, cmp))
    _write("io_table.tex", gen_io(ws))
    _write("neb_table.tex", gen_neb())
    print(f"wrote tables under {OUT}")


if __name__ == "__main__":
    main()
