#!/usr/bin/bash
# Run Cachegrind on examples/cachegrind_harness scenarios; emit JSON + RST include.
# Requires: valgrind, cargo. Deterministic instruction counts (I refs), not wall time.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT_DIR="${OUT_DIR:-$ROOT/docs/source/_generated}"
CG_DIR="${CG_DIR:-$ROOT/target/cachegrind}"
mkdir -p "$OUT_DIR" "$CG_DIR"

SCENARIOS=(
  parse_multi_2x4
  forward_multi_2x4
  convel_multi
  parse_100_frames
  forward_100_frames
  parse_cuh2_218
  float_fast_float2
  float_std_parse
  write_100_frames
)

echo "Building release harness..."
cargo build --release --example cachegrind_harness
BIN="$ROOT/target/release/examples/cachegrind_harness"
test -x "$BIN"

JSON="$OUT_DIR/cachegrind_results.json"
RST="$OUT_DIR/cachegrind_results.rst"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"

# Prefer --tool=cachegrind for I/D refs + miss rates (stable on GHA ubuntu).
run_cg() {
  local name="$1"
  local out="$CG_DIR/${name}.out"
  local log="$CG_DIR/${name}.log"
  # Isolate: one scenario per invocation so I refs are attributable.
  valgrind --tool=cachegrind \
    --cachegrind-out-file="$out" \
    --branch-sim=no \
    --error-exitcode=0 \
    "$BIN" "$name" >"$log" 2>&1 || true
  # Parse "I   refs:" line from summary (stderr merged in log)
  local irefs
  irefs=$(grep -E '^\s*I\s+refs:' "$log" | tail -1 | sed -E 's/.*I[[:space:]]+refs:[[:space:]]*([0-9,]+).*/\1/' | tr -d ',')
  if [[ -z "${irefs:-}" ]]; then
    # fallback: cg_annotate
    if command -v cg_annotate >/dev/null && [[ -f "$out" ]]; then
      irefs=$(cg_annotate "$out" 2>/dev/null | grep -E '^\s*I\s+refs' | head -1 | awk '{print $3}' | tr -d ',')
    fi
  fi
  echo "${irefs:-0}"
}

declare -A RESULTS
for s in "${SCENARIOS[@]}"; do
  echo "Cachegrind: $s"
  RESULTS[$s]=$(run_cg "$s")
  echo "  I refs = ${RESULTS[$s]}"
done

# JSON
{
  echo "{"
  echo "  \"generated_at\": \"$STAMP\","
  echo "  \"git_sha\": \"$SHA\","
  echo "  \"tool\": \"cachegrind\","
  echo "  \"metric\": \"I_refs\","
  echo "  \"note\": \"Instruction references counted by Valgrind Cachegrind on a fixed harness (examples/cachegrind_harness.rs). Not wall-clock; comparable across commits on the same CI image.\","
  echo "  \"scenarios\": {"
  local first=1
  for s in "${SCENARIOS[@]}"; do
    [[ $first -eq 1 ]] || echo ","
    first=0
    printf '    "%s": %s' "$s" "${RESULTS[$s]}"
  done
  echo ""
  echo "  }"
  echo "}"
} >"$JSON"

# RST include for Sphinx
cat >"$RST" << RSTEOF
.. cachegrind-results — generated by scripts/run_cachegrind_bench.sh; do not edit by hand.

.. list-table:: Cachegrind instruction counts (CI-refreshable)
   :header-rows: 1
   :widths: 40 25 35

   * - Scenario
     - I refs
     - Notes
   * - ``parse_multi_2x4`` (50× full parse)
     - ${RESULTS[parse_multi_2x4]}
     - 2-frame multi CON
   * - ``forward_multi_2x4`` (50× skip)
     - ${RESULTS[forward_multi_2x4]}
     - ``forward()`` line skip
   * - ``convel_multi`` (50×)
     - ${RESULTS[convel_multi]}
     - coords + velocities
   * - ``parse_100_frames`` (10×)
     - ${RESULTS[parse_100_frames]}
     - synthetic 100× tiny_cuh2
   * - ``forward_100_frames`` (10×)
     - ${RESULTS[forward_100_frames]}
     - skip mode
   * - ``parse_cuh2_218`` (20×)
     - ${RESULTS[parse_cuh2_218]}
     - 218-atom frame
   * - ``float_fast_float2`` (10k lines)
     - ${RESULTS[float_fast_float2]}
     - 5-column fast-float2
   * - ``float_std_parse`` (10k lines)
     - ${RESULTS[float_std_parse]}
     - 5-column ``str::parse``
   * - ``write_100_frames`` (10×)
     - ${RESULTS[write_100_frames]}
     - buffer writer

Generated **${STAMP}** from commit ``${SHA}`` on the Cachegrind CI runner
(``ubuntu-22.04`` + Valgrind). Lower **I refs** is better for the same
scenario. These numbers are **deterministic for a given binary and Valgrind
version**, unlike Criterion wall-clock medians, so they are suitable for
regression tracking on every ``main`` push.

Wall-clock tables elsewhere on this page are **indicative** (developer
machine / older Criterion runs) and may lag code changes; prefer Cachegrind
for “did this PR change the hot path?” and Criterion PR workflow for
latency intuition.
RSTEOF

echo "Wrote $JSON"
echo "Wrote $RST"
